server:
  port: 8082
spring:
  #mysql连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.117:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  #redis连接
  redis:
    database: 0
    host: 127.0.0.1
    port: 6378
    password: 123456
    jedis:
      pool:
        max-active: 9
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  #spring缓存配置
  cache:
    cache-names: menu_cache
    redis:
      time-to-live: 1800s #连接存货时间

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.hanmj.bean